<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Owner</title>
<link rel="stylesheet" type="text/css" href="../view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Owner</a></h1>
		<form id="form_981137" class="appnitro"  method="post" action="removeOwner.php">
					<div class="form_description">
					<a href=../template.html> <img src="../home.png" alt="Home" id="home_img"> </a>  
			<h2>Owner</h2>
			<p>Please Define If Owner Is a Private Owner Or a Company</p>
		</div>						
			<ul >
			
					<li id="li_1" >
		<label class="description" for="element_1">Owner Type </label>
		<span>
			<input id="element_1_1" name="element_1" class="element radio" type="radio" value="1" />
<label class="choice" for="element_1_1">Private</label>
<input id="element_1_2" name="element_1" class="element radio" type="radio" value="2" />
<label class="choice" for="element_1_2" >Company</label>

		</span> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="981137" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	
	<?php 

		if (isset($_POST['submit'])){	
			  $choice = $_POST['element_1'];
			  echo $choice;
			if ($choice==1){
				    header("Location: PrivateForm/removePrivate.php");
			}
			else	header("Location: CompanyForm/removeCompany.php");
			
			}
			?>
	</body>
</html>
