<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<title>Untitled Form</title>
<link rel="stylesheet" type="text/css" href="view.css" media="all">
<script type="text/javascript" src="view.js"></script>

</head>
<body id="main_body" >
	
	<img id="top" src="top.png" alt="">
	<div id="form_container">
	
		<h1><a>Untitled Form</a></h1>
		<form id="form_981161" class="appnitro"  method="post" action="">
					<div class="form_description">
			<h2>Untitled Form</h2>
			<p>This is your form description. Click here to edit.</p>

		</div>						
			<ul >
			
					<li id="li_1" >

		<?php 
			// create a connection to the database with
			// mysql_connect(servername, username, password) function
			$con = mysqli_connect("localhost","root","admin");
			if (!$con){
			 	die('Could not connect: ' . mysqli_error($con));
			}
			$db="Ideal Home";
			// a database must be selected before a query is executed on it
			mysqli_select_db($con,$db) or die('DB connection error' . mysqli_error($con));

			if ( isset($_POST['submit']) ){
				$result1 = mysqli_query($con,"DELETE FROM `Ideal Home`.`employee` WHERE `employee`.`Employee_ID` = 7");
			}
			mysqli_close($conn);
		
		 ?>
		<label class="description" for="Employee">Drop Down </label>
		<div>
		<select class="element select medium" id="element_1" name="Employee"> 
			<option value="" selected="selected"></option>
		<?php
			//Select data from a SELECT statement to show at the dropdown list
			$select = "SELECT `Employee_ID`,`Name` ,`Surname` FROM `employee`";
			$result = mysqli_query($con, $select);

			if (mysqli_num_rows($result) > 0) {
			    // output data of each row
			    while($row = mysqli_fetch_assoc($result)) {
				echo '<option name ="Employee" value="'.$row["Employee_ID"].'">'.$row['Name'].' '.$row['Surname'].'</option>
			';
			    }
			} else {
			    echo "0 results";
			}
		 ?>
		</select>
		</div> 
		</li>
			
					<li class="buttons">
			    <input type="hidden" name="form_id" value="981161" />
			    
				<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
		</li>
			</ul>
		</form>	
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
	</body>
</html>
